---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{name}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: {{labels_app}} 
    spec:
      containers:
      - name: {{container_name}}
        image: {{container_image}}
        ports:
        - containerPort: {{container_port}}
