apiVersion: v1
kind: Service
metadata:
  name: {{name}}
spec:
  selector:
    app: {{selector_app_name}}
  ports:
  - protocol: TCP
    port: {{port}}
    targetPort: {{target_port}}
  type: LoadBalancer